[project]
name = "galspectra"
version = "0.1.0"
description = "SED generation and PCA-based analysis pipeline for galaxy spectra"
authors = [{name="Suttikoon"}]
dependencies = [
    "numpy",
    "scipy",
    "scikit-learn",
    "pyyaml",
    "astropy",
    "matplotlib",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
galspectra = "galspectra.cli:main"
